apiVersion: v1
kind: ConfigMap
metadata:
  name: homepage-config
data:
  settings.yaml: |
    title: Homelab
  services.yaml: |
    - Infrastructure:
        - ArgoCD:
            href: https://argocd.home.server
            description: GitOps
        - Traefik:
            href: https://traefik.home.server
            description: Reverse proxy
        - Pi-hole:
            href: https://pihole.home.server
            description: DNS / ad-blocking

    - Media:
        - Plex:
            href: https://plex.home.server
            description: Media server

    - Monitoring:
        - Sentinel:
            href: https://sentinel.home.server
            description: Disk health

  

  widgets.yaml: |
    []
  bookmarks.yaml: |
    []