services:
  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Baku
    volumes:
      - ./config:/config
      - /mnt/storage/films:/media
      - /mnt/storage/films/downloads:/downloads

    ports:
      - 8989:8989
    restart: unless-stopped
    networks:
      - mediastack

networks:
  mediastack:
    external: true
