http:
  middlewares:
    redirect-to-https:
      redirectScheme:
        scheme: https
        permanent: true

    # Optional but recommended security headers (we can tune later)
    security-headers:
      headers:
        browserXssFilter: true
        contentTypeNosniff: true
        forceSTSHeader: true
        stsIncludeSubdomains: true
        stsPreload: true
        stsSeconds: 31536000
        customFrameOptionsValue: "SAMEORIGIN"
