http:
  routers:
    plex:
      rule: "Host(`plex.home.server`)"
      entryPoints:
        - websecure
      tls: {}
      service: plex
      middlewares:
        - security-headers@file

    plex-http:
      rule: "Host(`plex.home.server`)"
      entryPoints:
        - web
      service: plex
      middlewares:
        - redirect-to-https@file

  services:
    plex:
      loadBalancer:
        servers:
          - url: "http://192.168.100.6:32400"
