services:
  plex:
    image: lscr.io/linuxserver/plex:latest
    container_name: plex
    restart: unless-stopped
    network_mode: host

    environment:
      - TZ=Asia/Tehran

    volumes:
      - /home/rezayaghobi/docker/plex:/config
      - /mnt/storage:/media
