services:
  radarr:
    image: lscr.io/linuxserver/radarr:latest
    container_name: radarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Baku
    volumes:
      - ./config:/config
      - /mnt/storage/films:/media
      - /mnt/storage/films/downloads:/downloads

    ports:
      - 7878:7878
    restart: unless-stopped
    networks:
      - mediastack

networks:
  mediastack:
    external: true
