IMAGE_Debian_12 = "bento/debian-12"

Vagrant.configure("2") do |config|
  config.vm.box = IMAGE_Debian_12
  config.vm.box_check_update = false

  config.vm.hostname = "test"

  config.vm.network "private_network", ip: "192.168.56.10"

  config.vm.provider "virtualbox" do |vb|
    vb.name = "my_vm"
    vb.memory = 1024
    vb.cpus = 1
  end
end
