services:
  dockscope:
    image: ghcr.io/manuelr-t/dockscope:latest
    container_name: dockscope
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    restart: unless-stopped
    networks:
      - web_net
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=web_net"
      # HTTPS
      - "traefik.http.routers.dockscope.rule=Host(`dockscope.home.server`)"
      - "traefik.http.routers.dockscope.entrypoints=websecure"
      - "traefik.http.routers.dockscope.tls=true"
      - "traefik.http.routers.dockscope.service=dockscope"
      - "traefik.http.routers.dockscope.middlewares=security-headers@file,dockscope-auth@file"
      # HTTP → HTTPS redirect
      - "traefik.http.routers.dockscope-http.rule=Host(`dockscope.home.server`)"
      - "traefik.http.routers.dockscope-http.entrypoints=web"
      - "traefik.http.routers.dockscope-http.middlewares=redirect-to-https@file"
      # Internal port
      - "traefik.http.services.dockscope.loadbalancer.server.port=4681"

networks:
  web_net:
    external: true