apiVersion: 1
contactPoints:
  - orgId: 1
    name: gmail-alerts
    receivers:
      - uid: gmail-email-receiver
        type: email
        settings:
          addresses: YOUR_EMAIL@example.com
          singleEmail: true
